export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_STUDENT_NULL = "SET_STUDENT_NULL";
export const LOADING_USER = "LOADING_USER";
export const LOADING_LOGOUT = "LOADING_LOGOUT";

export const OPEN_PATIENT = "OPEN_PATIENT";
export const LOADING_OPEN_PATIENT = "LOADING_OPEN_PATIENT";
export const PATIENT_ERRORS = "PATIENT_ERRORS";
export const GET_RESULTS = "GET_RESULTS";
export const LOADING_RESULTS = "LOADING_RESULTS";

export const GET_MEDICINE = "GET_MEDICINE";
export const LOADING_MEDICINE = "LOADING_MEDICINE";

export const ADD_RESULT = "ADD_RESULT";
export const ADD_MEDICINE = "ADD_MEDICINE";
export const LOADING_ADD_MEDICINE = "LOADING_ADD_MEDICINE";
export const LOADING_ADD_RESULT = "LOADING_ADD_RESULT";

export const GET_CHATS = "GET_CHATS";
export const AFTER_POST_MESSAGE = "AFTER_POST_MESSAGE";
